INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Pizzas');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Massas');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Cereais') ;
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Queijos');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Iogurtes');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Leites & Achocolatados');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('frangoAves');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Carne bovina');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Carne suína');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Embutidos');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Frutos do mar');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Ovos');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Peixes');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Frutas');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Verduras & Legumes');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Bolos & Doces');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Chocolates');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Bebidas não alcoólicas');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Bebidas alcoólicas');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Salgadinhos & Petiscos');
INSERT INTO tb_tipos_de_alimentos (nome_tipo_alimento) VALUES ('Sanduíches');